version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      root-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/packages/tints-and-shades"
    schedule:
      interval: "monthly"
    groups:
      package-dependencies:
        patterns:
          - "*"